name: Deploy Snapshot

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Deploy to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
        run: xvfb-run mvn -B deploy -X
